### ISSUE TITLE
TODO addons

### ISSUE THREAD

**Issue by EdyTheCow** [BeefBytes/GmodHQ-issues#19]
- [x] remove knockout bat
- [x] remove hitman addon
- [ ] fix arms  dealer player model
- [x] add new florida map to client workshop
- [x] update addons on workshop both client and server
- [x]  radio doesnt work
